version: "3.0"

services:
  app:
    build:
      context: ./docker
      dockerfile: app.dockerfile
    tty: true
    env_file:
      - ./docker/app.env.local
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
      - 4000:4000
    command: yarn dev
